name: Release Alpha Test 1

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Create release tag with timestamp
      id: tag
      run: echo "TAG=alpha-test-$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Alpha Test 1
        tag_name: ${{ steps.tag.outputs.TAG }}
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/mapping/release/mapping.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
