name: Release Alpha Test 4

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code (full history so source zips include tags/commits)
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up JDK 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. Ensure gradlew is executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # 5. Clean & build the debug APK
      - name: Build debug APK
        run: ./gradlew clean assembleDebug

      # 6. Create a timestamped tag value for this run
      - name: Create release tag
        id: tag
        run: |
          echo "TAG=alpha-test-$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      # 7. Create the GitHub Release and upload the one debug APK
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: Alpha Test 1
          files: |
            app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
