name: "Alpha Test release 9"

permissions: write-all

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '17'
  ANDROID_API: '34'
  BUILD_TOOLS: '34.0.0'

jobs:
  debug-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API }}
          build-tools: ${{ env.BUILD_TOOLS }}

      - run: chmod +x ./gradlew

      - run: ./gradlew clean assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: naiko-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release Naiko ${{ steps.extract_version.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API }}
          build-tools: ${{ env.BUILD_TOOLS }}

      - run: chmod +x ./gradlew

      - name: Extract version from tag
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - run: ./gradlew clean assembleStandardRelease

      - run: |
          git archive --format=zip HEAD -o source.zip
          git archive --format=tar.gz HEAD -o source.tar.gz

      - name: Prepare artifacts & checksums
        id: prep
        run: |
          RELEASE=${{ steps.extract_version.outputs.version }}
          mkdir artifacts
          declare -A SPLITS=(
            [7v]="app-standard-armeabi-v7a-release-unsigned.apk"
            [8v]="app-standard-arm64-v8a-release-unsigned.apk"
            [x86]="app-standard-x86-release-unsigned.apk"
            [x64]="app-standard-x86_64-release-unsigned.apk"
            [universal]="app-standard-universal-release-unsigned.apk"
          )
          for TYPE in "${!SPLITS[@]}"; do
            SRC="app/build/outputs/apk/standard/release/${SPLITS[$TYPE]}"
            [[ -f "$SRC" ]] && cp "$SRC" "artifacts/Naiko ${RELEASE} ${TYPE}.apk"
          done
          cp source.zip    "artifacts/Naiko ${RELEASE} source.zip"
          cp source.tar.gz "artifacts/Naiko ${RELEASE} source.tar.gz"
          {
            echo "| File | SHA-256 |"
            echo "|------|---------|"
            for F in artifacts/*; do
              H=$(sha256sum "$F"|cut -d' ' -f1)
              echo "| $(basename "$F") | \`$H\` |"
            done
          } > artifacts/checksums.md

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Naiko ${{ steps.extract_version.outputs.version }}"
          body_path: artifacts/checksums.md
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
