name: "Alpha release test 7"

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}–${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '17'
  ANDROID_API: '34'
  BUILD_TOOLS: '34.0.0'

jobs:
  # Always publish a Debug APK on pushes to main
  debug-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build Debug APK
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API }}
          build-tools: ${{ env.BUILD_TOOLS }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Naiko-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/app-debug.apk

  # On tag pushes to main, build release splits, package, checksum, and draft a GitHub Release
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Release Naiko ${{ github.ref_name#refs/tags/ }}

    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API }}
          build-tools: ${{ env.BUILD_TOOLS }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build all standard-Release splits
        run: ./gradlew clean assembleStandardRelease

      - name: Package source code
        run: |
          git archive --format=zip HEAD -o source.zip
          git archive --format=tar.gz HEAD -o source.tar.gz

      - name: Prepare artifacts & checksums
        id: prep
        run: |
          # strip 'v' prefix
          RELEASE=${GITHUB_REF#refs/tags/v}
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

          mkdir -p artifacts

          declare -A SPLITS=(
            [7v]="app-standard-armeabi-v7a-release-unsigned.apk"
            [8v]="app-standard-arm64-v8a-release-unsigned.apk"
            [x86]="app-standard-x86-release-unsigned.apk"
            [x64]="app-standard-x86_64-release-unsigned.apk"
            [universal]="app-standard-universal-release-unsigned.apk"
          )

          # Copy & rename APK splits with spaces
          for TYPE in "${!SPLITS[@]}"; do
            SRC="app/build/outputs/apk/standard/release/${SPLITS[$TYPE]}"
            if [[ -f "$SRC" ]]; then
              DST="artifacts/Naiko ${RELEASE} ${TYPE}.apk"
              cp "$SRC" "$DST"
            fi
          done

          # Copy source archives
          cp source.zip    "artifacts/Naiko ${RELEASE} source.zip"
          cp source.tar.gz "artifacts/Naiko ${RELEASE} source.tar.gz"

          # Generate checksums table
          {
            echo '| File | SHA-256 |'
            echo '|------|---------|'
            for F in artifacts/*; do
              H=$(sha256sum "$F" | awk '{print $1}')
              echo "| $(basename "$F") | \`$H\` |"
            done
          } > artifacts/checksums.md

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name#refs/tags/ }}
          name: "Naiko ${{ github.ref_name#refs/tags/ }}"
          body_path: artifacts/checksums.md
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
