# .github/workflows/android-release.yml
name: Release Alpha Test 2

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build all Release splits
        run: ./gradlew clean assembleRelease

      - name: Package source
        run: |
          zip -r source.zip .
          tar -czf source.tar.gz .

      - name: Create release tag
        id: tag
        run: echo "TAG=alpha-test-$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Rename APKs and prepare artifacts folder
        run: |
          mkdir artifacts
          for apk in app/build/outputs/apk/release/*-armeabi-v7a-release.apk \
                     app/build/outputs/apk/release/*-arm64-v8a-release.apk \
                     app/build/outputs/apk/release/*-x86-release.apk \
                     app/build/outputs/apk/release/*-x86_64-release.apk \
                     app/build/outputs/apk/release/*-universal-release.apk; do
            # Determine the “type” suffix
            case "$apk" in
              *armeabi-v7a*) TYPE="7v" ;;
              *arm64-v8a*)  TYPE="8v" ;;
              *x86_64*)     TYPE="x64" ;;
              *x86-release*)TYPE="x86" ;;
              *universal*)  TYPE="universal" ;;
            esac
            # Construct new filename
            fname="Naiko_${{ steps.tag.outputs.TAG }}_${TYPE}.apk"
            cp "$apk" "artifacts/$fname"
          done
          # Copy source archives
          cp source.zip   artifacts/Naiko_${{ steps.tag.outputs.TAG }}_source.zip
          cp source.tar.gz artifacts/Naiko_${{ steps.tag.outputs.TAG }}_source.tar.gz

      - name: Generate checksum table
        run: |
          echo "| File | SHA256 |" > artifacts/checksums.md
          echo "|------|--------|" >> artifacts/checksums.md
          for f in artifacts/*; do
            hash=$(sha256sum "$f" | cut -d ' ' -f1)
            echo "| $(basename "$f") | \`$hash\` |" >> artifacts/checksums.md
          done

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: "Alpha Test 1"
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
